name: Build Android app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: ./configure.sh
    - name: "Build Android project (ARCore research variant)"
      run: "./gradlew assembleArcoreResearchDebug"
